/*
 * This source file was generated by the Gradle 'init' task
 */
package projectgrow;


import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void testAplikasi() {
        // Test sederhana untuk memastikan 1 selalu sama dengan 1 (pasti lolos)
        assertEquals(1, 1);
    }
}
