/*
 * This source file was generated by the Gradle 'init' task
 */
package projectgrow;
import javafx.application.Application;
import javafx.stage.Stage;
import javafx.scene.Scene;
import javafx.scene.layout.StackPane;
import javafx.scene.control.Button;
public class App extends Application {
    @Override
    public void start(Stage primaryStage){
        primaryStage.setTitle("My Javafx");

        StackPane layout = new StackPane();

        Button button = new Button("Click me!");
        layout.getChildren().add(button);

        Scene scene = new Scene(layout, 300, 250);

        primaryStage.setScene(scene);

        primaryStage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}